### ISSUE TITLE
Search bar is illegible in few screens

### ISSUE THREAD

**Issue by saswatamcode** [graphql/graphql.github.io#1006]
### Description

The search bar is illegible in the index screen, after scrolling down from the hero container and selecting the search bar. The hero search bar and and header search bar seem to overlap. And in screens such as Community, the search bar pops out of the navbar on focus and the search bar being transparent becomes illegible.

### Steps to Reproduce
Visit [site](https://graphql.org/), scroll down and select search bar. Visit [community page](https://graphql.org/community/) scroll down and select search bar.

Chrome Version:  88.0.4324.182 (Official Build) (x86_64)
macOS Version: 10.15.5

### Screenshots
- header and hero overlap
![Screenshot 2021-02-20 at 12 33 23 PM](https://user-images.githubusercontent.com/51132453/108587149-04e02400-7378-11eb-88c1-4487350127a0.png)
- community screen
![Screenshot 2021-02-20 at 12 33 43 PM](https://user-images.githubusercontent.com/51132453/108587151-0873ab00-7378-11eb-8c05-7aeb9166b67d.png)

### Related issues
#831

**Comment by ziunadev** [comment]
### The bug still live
I think I still get the bug. I was visited graphql.org recently, suddenly when I'm trying to search something the bug appears

### Screenshot

- On white screen after i scrolled the screen

![image](https://user-images.githubusercontent.com/71458677/111936523-6ec72700-8af8-11eb-8a26-aa2786cb738a.png)

- When dark navbar overlapping the white

![image](https://user-images.githubusercontent.com/71458677/111936699-da10f900-8af8-11eb-96c1-65c172a8a70e.png)

### Related Issue
[#831](https://github.com/graphql/graphql.github.io/issues/831)
