### ISSUE TITLE
Updates of this repo is not reflected to https://graphql.github.io

### ISSUE THREAD

**Issue by jihoon-seo** [graphql/graphql.github.io#1021]
### Description

- The default branch of this repo is `source`.
- The latest commit of the `source` branch was on Mar 10, 2021. ([Link](https://github.com/graphql/graphql.github.io/commits/source))
- But the last deployment to `https://graphql.github.io` by `github-pages` was on 16 Oct 2020. ([Link](https://github.com/graphql/graphql.github.io/deployments))
  - It seems that this is because the latest commit of the `master` branch was on 16 Oct 2020. ([Link](https://github.com/graphql/graphql.github.io/commits/master))
- This causes the website `https://graphql.github.io` to be outdated.
  - [Evidences]
  - In the footer, the [`Edit this page`](https://github.com/graphql/graphql.github.io/edit/source/site/index.html.js) link is broken.
  - In the footer, the menu items of `https://graphql.github.io` is different from those of `https://graphql.org`.
    - [The menu items of `https://graphql.github.io`]
  ![image](https://user-images.githubusercontent.com/46767780/110881918-7c282880-8324-11eb-86a6-f72bac8b83d0.png)
    - [The menu items of `https://graphql.org`]
  ![image](https://user-images.githubusercontent.com/46767780/110881981-98c46080-8324-11eb-80bc-d7d646747d4d.png)
  - Same issue for `https://graphql-kr.github.io` (The Korean-version website), and so on..

  

### Steps to Reproduce

- Check the links in the `Description` section above.
- Visit https://graphql.github.io
- Visit https://graphql.org

### Expected Result 

- The website `https://graphql.github.io` is updated whenever a new commit is pushed to the `source` branch.

### Actual Result 

- The website `https://graphql.github.io` is **not** updated even if a new commit is pushed to the `source` branch.
- In contrast, The website `https://graphql.org` seems to be updated whenever a new commit is pushed to the `source` branch.

**Comment by saihaj** [comment]
`https://graphql.org` is hosted on Netlify and pushes to `source` get deployed that is why `master` branch is not synced. It is possible to have a GH action that will deploy the `source` to `master` (but seems waste of resources) or we can setup redirect from `graphql.github.io` -> `graphql.org`. 
@orta @IvanGoncharov thoughts?

**Comment by jihoon-seo** [comment]
@saihaj Thank you for your comment.

I think that one with proper privilege can change the source branch of `https://graphql.github.io` from `master` to `source`
at https://github.com/graphql/graphql.github.io/settings

---

![image](https://user-images.githubusercontent.com/46767780/110884881-23a75a00-8329-11eb-8004-1a3ecc7429d5.png)

**Comment by saihaj** [comment]
Yes but the issue is that this is a Gatsby site and we need to build it in order for GH pages to deploy. So can't just change the branch for GH pages

**Comment by brianwarner** [comment]
I can confirm we build with netlify from the `source` branch, which is also the primary branch in this repo. My guess is that things probably just need to be merged.

@orta, @carolstran, @IvanGoncharov do you mind if I go through and merge the obvious ones?

**Comment by orta** [comment]
Oof, this is a bit gnarly, I think the only reasonable answer here is that pushed to `source` trigger a GitHub action to deploy the build version of the site to graphql.github.io 

If we don't do that then we break any existing links

**Comment by brianwarner** [comment]
It just clicked for me (sorry I'm slow this week...) that we have two site generators involved here. I agree @orta, it will get gnarly to keep the legacy GitHub Pages site (which as @jihoon-seo mentions was built from `master`) in sync with the current Gatsby site (e.g., `source`). It will get gnarlier as we add features and content to the Gatsby site, and we have two identical looking but increasingly divergent sites.

It looks like GitHub has approved a redirect plugin for Jekyll. While we could go through and try to keep things in sync, would there be significant negative effects if we just do a generic redirect from graphql.github.io to graphql.org?

**Comment by orta** [comment]
Yeah, we'd need to add redirects for every existing page because the redirects plugin just [uses a HTML + JS file](https://github.com/jekyll/jekyll-redirect-from/blob/master/lib/jekyll-redirect-from/redirect.html) which means we'll be doing a bunch of work to make the redirects happen aka there's no DNS settings for this

I think a double deploy is probably the right answer

**Comment by brianwarner** [comment]
I worry a little about things getting out of sync if we are maintaining the same content on parallel sites. 

That said, if the Jekyll site doesn't hasn't been updated, then the number of pages on the graphql.github.io version of the site should be a fixed number. It would be painful, but hopefully "only one time" painful, to put individual redirects in place for each page on the old site, pointing to its counterpart on graphql.org. New content, like the /foundation/ pages, would never exist on the Jekyll site so nobody would ever link to graphql.github.org/foundation, for example.

I think we might be able to solve this permanently by setting up the Jekyll site this way and forgetting it? What do you think?

**Comment by brianwarner** [comment]
@orta, I did a little playing around tonight, would you mind taking a look at #1025? I basically scraped for all .html pages and replaced them with a stub index file that uses meta refresh to do the forwarding.

It's not exactly the most elegant of solutions elegant, but it should have a minimal risk of human error and require no maintenance... I hope...

**Comment by jihoon-seo** [comment]
- This issue was resolved by #1025
