### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by Carthanial** [graphql/graphql.github.io#1027]
### Description

The website never loads. Have tested it with down detector type sites and they come back the same.

### Steps to Reproduce

Visit graphql.org in your browser

### Expected Result 

The website to load.

### Actual Result 

Buffer circle animation never stopping.

### Additional Context

The browser I use is firefox

**Comment by saihaj** [comment]
Whenever Netlify fixes CDN issue site should be up https://www.netlifystatus.com

**Comment by brianwarner** [comment]
I've requested a DNS change to switch to their new load balancer, per the guidance on the status page.

**Comment by mikeesto** [comment]
Looks to be resolved now 👍

**Comment by benjie** [comment]
Agreed
