### ISSUE TITLE
Search Input Field Overlaps The Text

### ISSUE THREAD

**Issue by adithyaakrishna** [graphql/graphql.github.io#1030]
### Description
When I visited the [GraphQL Learn Page](https://graphql.org/learn/), and wanted to search for a topic, I clicked on the search field and saw this bug with the input field

### Steps to Reproduce
Click on the search bar, the search field overlaps the text
![image](https://user-images.githubusercontent.com/23498248/112889107-d67e0300-90f2-11eb-9c36-8ceddf960c83.png)

### Expected Result 
The text shouldn't be visible i.e. the Search Input field should have a color fill

- **Willing to Work on this,**
Yes :)

**Comment by mikeesto** [comment]
Before you start working on it, I believe it has been fixed in this open PR: https://github.com/graphql/graphql.github.io/pull/1019#issuecomment-799722063

**Comment by hwillson** [comment]
Fixed by https://github.com/graphql/graphql.github.io/pull/1019 - thanks!
