### ISSUE TITLE
DOCS: invalid/404 link in docs.

### ISSUE THREAD

**Issue by aghArdeshir** [graphql/graphql.github.io#1055]
In documentation of graphql, Validation page (https://graphql.org/learn/validation/) there is a link in second paragraph, pointing to a file in github. but github return 404 Not Found.

This is where the link points to: https://github.com/graphql/graphql-js/blob/main/src/__tests__/starWarsValidation-test.js

**Comment by aghArdeshir** [comment]
There is another one in https://graphql.org/learn/introspection/

**Comment by brianwarner** [comment]
Good catch @aghArdeshir, PR inbound shortly.
