### ISSUE TITLE
Enabling OAuth App access restrictions for your organization on GitHub

### ISSUE THREAD

**Issue by saboyutaka** [graphql/graphql.github.io#1060]
I'm touching with the GitHub API v4 Explorer and found that the GraphQL organization does not allow OAuth app access.

Is there any reason for this? If it allow OAuth App access restrictions, it would be a good example of how to use GraphQL.

https://docs.github.com/ja/graphql/overview/explorer
https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data

<img width="833" alt="Explorer_-_GitHub_Docs" src="https://user-images.githubusercontent.com/1701108/123353557-bdbfa500-d59c-11eb-970a-d84867a85f1f.png">

**Comment by hwillson** [comment]
👋 @saboyutaka - I don't think loosening OAuth app access is something that is going to happen anytime soon (but I'm sure others will chime in and correct me if I'm wrong 😅). There are a bunch of great folks across the community that help the GraphQL Foundation in tons of different ways, many of which have org / collaborator levels of access within the `graphql` org. Disabling OAuth app access restrictions means some of those members could authorize an OAuth app to get access to the org's private resources. Even though this isn't something they would ever do maliciously, this is one of those things that would be better to just not ever have to worry about by keeping the restriction in place. Thanks for the suggestion though!
