### ISSUE TITLE
add toggle for alphabetical sort of language list in /code

### ISSUE THREAD

**Issue by ghost** [graphql/graphql.github.io#1107]
### Description

only one html/css change requred, reference implementation:
https://codepen.io/dym-sh/pen/gORLrGQ?editors=1100

- also add Dart as alias for Flutter
- also set column-count to auto, no need for screen-size-breakpoints dependency

### Motivation

so, in https://graphql.org/code/
i was scanning the list for Dart, but only found Flutter after i started going one-by-one
both of which would be way faster if list would be in alphabetical order and had Dart

### Collaboration

sure.. not sure if its something important enough, so just an issue atm, i can prob send PR within a week

**Comment by Urigo** [comment]
that's a good idea, we would love to accept a PR for that change
