### ISSUE TITLE
`Buffer is not defined` error in Variables example

### ISSUE THREAD

**Issue by saiskee** [graphql/graphql.github.io#1126]
### Description

Seeing the error `Buffer is not defined` in this query: https://graphql.org/learn/queries/#using-variables-inside-fragments

### Steps to Reproduce

Visit https://graphql.org/learn/queries/#using-variables-inside-fragments

### Expected Result 

The query would work as expected
![image](https://user-images.githubusercontent.com/1731122/134364140-c8ea956b-afc3-45e6-bc32-a9f81f3f3624.png)

**Comment by robz** [comment]
The same issue is on the pagination section: https://graphql.org/learn/pagination/#complete-connection-model

**Comment by Urigo** [comment]
if someone wants to give it a shot, here is the [schema](https://github.com/graphql/graphql.github.io/blob/source/src/components/Marked/swapiSchema.tsx) and the [execution](https://github.com/graphql/graphql.github.io/blob/source/src/components/Marked/MiniGraphiQL.tsx)

**Comment by Arthur-Milchior** [comment]
Issue still exists
