### ISSUE TITLE
The instructions at "Getting Started With GraphQL.js" are not working

### ISSUE THREAD

**Issue by fskuteken** [graphql/graphql.github.io#1168]
### Description

The instructions at the page [Getting Started With GraphQL.js](https://graphql.org/graphql-js/) didn't work for me.
Even though the page mentions Node v6, I expected that it should work on more recent versions as well.

### Steps to Reproduce

Follow the instructions at https://graphql.org/graphql-js/:
1. `npm init`
2. `npm install graphql --save`
3. Create the `server.js file`

```javascript
var { graphql, buildSchema } = require('graphql');

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type Query {
    hello: String
  }
`);

// The root provides a resolver function for each API endpoint
var root = {
  hello: () => {
    return 'Hello world!';
  },
};

// Run the GraphQL query '{ hello }' and print out the response
graphql(schema, '{ hello }', root).then((response) => {
  console.log(response);
});
```
4. Run `node server.js`

### Expected Result 

`{ data: { hello: 'Hello world!' } }`

### Actual Result 

> UnhandledPromiseRejectionWarning: Error: Expected undefined to be a GraphQL schema.

### Additional Context

The installed package version was "graphql": "^16.0.1".
The node version I used was v14.17.0.

**Comment by notrab** [comment]
Hey @fskuteken 

I've submitted a PR to fix this.

If you update the last part to be the following, it'll work:

```js
graphql({ schema, source: '{ hello }', rootValue: root }).then((response) => {
  console.log(response);
});
```

**Comment by hwillson** [comment]
This was fixed by https://github.com/graphql/graphql.github.io/pull/1186 - closing, thanks!
