### ISSUE TITLE
"Using variables inside fragments" code example has errors

### ISSUE THREAD

**Issue by snoopdougiedougie** [graphql/graphql.github.io#1189]
### Description

The code example in https://graphql.org/learn/queries/#using-variables-inside-fragments shows the following errors:

```
{
  "errors": [
    {
      "message": "Buffer is not defined",
      "locations": [
        {
          "line": 12,
          "column": 3
        }
      ],
      "path": [
        "leftComparison",
        "friendsConnection"
      ]
    },
    {
      "message": "Buffer is not defined",
      "locations": [
        {
          "line": 12,
          "column": 3
        }
      ],
      "path": [
        "rightComparison",
        "friendsConnection"
      ]
    }
  ],
  "data": {
    "leftComparison": null,
    "rightComparison": null
  }
}
```

### Steps to Reproduce

Navigate to the link.

### Expected Result 

No errors.

### Actual Result 

Errors

### Additional Context

none

**Comment by hwillson** [comment]
Thanks @snoopdougiedougie - I'm not seeing the same thing currently; maybe this was fixed / resolved itself? Let us know if you see this happen again. 

![CleanShot 2022-11-12 at 19 01 57](https://user-images.githubusercontent.com/137740/201499358-60d864a8-2a63-41db-ae17-5b0a5df876cb.png)
