### ISSUE TITLE
Link for graphql-kotlin docs gives "page not found error"

### ISSUE THREAD

**Issue by MadhaviMandalia** [graphql/graphql.github.io#1192]
### Description
Page not found for graphql-kotlin docs in GraphQL website 

### Steps to Reproduce

1. Visit https://graphql.org/code/#java-kotlin
2. Click on [`graphql-kotlin docs`](https://opensource.expediagroup.com/graphql-kotlin/docs/getting-started)

**Comment by MadhaviMandalia** [comment]
Please let me know if I can raise a PR for this do provide me the correct link

Thanks & Regards.

**Comment by orta** [comment]
Yep, no need to wait for permission to fix a broken link in a PR 👍🏻

**Comment by MadhaviMandalia** [comment]
@orta can you provide me the link for documentation?

Thanks & Regards.

**Comment by orta** [comment]
There's docs in the README: https://github.com/graphql/graphql.github.io#how-to-contribute
