### ISSUE TITLE
'Example' anchor links are all named #example

### ISSUE THREAD

**Issue by kevinSuttle** [graphql/graphql.github.io#12]
I know this is because they're `####` compiling to `h4`, but it would seem to be a better UX to give each section example its own named anchor link.

e.g. http://graphql.org/docs/api-reference-type-system/

**Comment by stubailo** [comment]
In other docs I work on, we don't use `###` headings at all, for this reason and also because it means you can't change the heading text without breaking links to that heading.

Perhaps always using `<h3 id="my-section">My section</h3>` could be a good style rule.
