### ISSUE TITLE
GraphQL with Optional parameters (Java + Angular-Apollo)

### ISSUE THREAD

**Issue by Bilel-NEJI** [graphql/graphql.github.io#1216]
Hi everybody,
I'm building a GraphqlQL server using Quarkus and I want to consume its endpoint with apollo-angular.
And I need to filter the data in the backend (not filtering in the frontend). So I use a resource method with optional parameters:

    @GraphQLApi
    public class McsClientResource {

    @Inject
    McsClientImpl service;

    @Query("allDevices")
    @Description("Get all devices of one user")
    public GetAllDomesticDevicesOutMiTO getAllDevices(
            Optional<Integer> optState,
            Optional<String> optUserId,
            Optional<String> dft) {
        if(!optUserId.isEmpty()){
            return  service.getAllDevices().get(optUserId.get());} 
                  else { return  service.getAllDevices().get("User0");  }
         }
     }

This is the query that I use the graphql-ui to test, and it works:

     query getAllDevices {
         allDevices (optUserId: "User0"){
            devices {
              deviceName
              deviceState
              deviceType
              miDeviceId
       }
    }
}

But for me I need display a **filtred** (in the backend side) result in a table.
So how should I do? Should I use variables or what?

**Comment by hwillson** [comment]
👋 @Bilel-NEJI - this type of question is better asked elsewhere, like in the [GraphQL Foundation Discord](https://discord.graphql.org/). Issues here are reserved for problems / feature requests regarding the https://graphql.org site. Thanks!
