### ISSUE TITLE
Order of the "Queries and Mutation" sections on the Learn Page

### ISSUE THREAD

**Issue by OliverSieweke** [graphql/graphql.github.io#1246]
Thank you for the very readable and well organized [_Learn_](https://graphql.org/learn/) material on the website. This is just to propose a slight change in the order of the sections of the [_Query and Mutation_](https://graphql.org/learn/queries/) page.

The [_Operations Name_](https://graphql.org/learn/queries/#operation-name) section specifies:
> Up until now, we have been using a shorthand syntax where we omit both the query keyword and the query name

Which is not quite true as the previous [_Fragments_](https://graphql.org/learn/queries/#fragments) section provides the following example:

```graphql
query HeroComparison($first: Int = 3) {
  leftComparison: hero(episode: EMPIRE) {
    ...comparisonFields
  }
  rightComparison: hero(episode: JEDI) {
    ...comparisonFields
  }
}
```

It might therefore make sense to swap around the order of the  [_Fragments_](https://graphql.org/learn/queries/#fragments) and [_Operations Name_](https://graphql.org/learn/queries/#operation-name) sections.

**Comment by Lokprakash-babu** [comment]
Hi,

Raised a [PR](https://github.com/graphql/graphql.github.io/pull/1252). Hopefully, this will resolve the issue.
