### ISSUE TITLE
Sticky Sidebar for better reading 

### ISSUE THREAD

**Issue by Lokprakash-babu** [graphql/graphql.github.io#1247]
### Description

When a reader scrolls to the bottom of the doc, they have to go all the way to the top to navigate to other doc links. If the sidebar is sticky, it will be a good UX. 

### Motivation

When I was reading the doc, in order to see the options available in the sidebar, once I finished a particular page, I would have to scroll all the way to top again. This becomes annoying if we keep on repeating, so I used to edit the style property from the dev tools.

### Collaboration

I want to build it out. 

### Additional Context

This will provide a good UX.

**Comment by Urigo** [comment]
I think this is fixed now thanks to @dimaMachina's refactoring!
Please reopen if that's not the case
