### ISSUE TITLE
Access to push to repo to add JS graphql client and server

### ISSUE THREAD

**Issue by miami-man** [graphql/graphql.github.io#1286]
Hi,

I would like to raise a PR to add a JS graphql client and server to the `code/language-support/javascript section. Is this something I can raise a PR for or is there another process through which libraries can get added to this section?

For reference, the library I'd like to add is https://github.com/badbatch/graphql-box/.

Cheers,
D

**Comment by orta** [comment]
Feel free to send a pull request, yep

**Comment by hwillson** [comment]
@dylanaubrey we'll go ahead and close this off since Orta answered in https://github.com/graphql/graphql.github.io/issues/1286#issuecomment-1312257465. Fire over a PR when ready. Thanks!

**Comment by miami-man** [comment]
thanks... I cloned the repo and created a branch and was not able to push the branch to the remote, says I don't have access... `ERROR: Permission to graphql/graphql.github.io.git denied to dylanaubrey.`... do you need to add me to list of contributors or something?

**Comment by orta** [comment]
I'd recommend learning how pull requests and forks work on GitHub: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by miami-man** [comment]
I have raised a PR https://github.com/graphql/graphql.github.io/pull/1311... it has some build errors... could someone assist? cheers.
