### ISSUE TITLE
graphql-js error encountered in the `/learn` pages

### ISSUE THREAD

**Issue by jfcisco** [graphql/graphql.github.io#1307]
### Description

Instead of showing the result of the GraphQL query in the web page, the output box shows an error.

### Steps to Reproduce

1. Open a browser and navigate to either of the following:
    - https://graphql.org/learn/queries/#fields
    -  https://graphql.org/learn/schema/#union-types

### Expected Result 

The field name returns a String type, in this case the name of the main hero of Star Wars, "R2-D2".

### Actual Result 

`data` property is null and an `error` is shown in the output box. For example, the /learn/queries/#fields section shows this error:

```json
{
  "errors": [
    {
      "message": "Support for returning GraphQLObjectType from resolveType was removed in graphql-js@16.0.0 please return type name instead.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "hero"
      ]
    }
  ],
  "data": {
    "hero": null
  }
}
```

### Additional Context

I was able to reproduce the issue on Chrome 107.0.5304.107 and Firefox Developer Edition 107.0b9 (64-bit)

![image](https://user-images.githubusercontent.com/9131226/201880576-0372efde-07d6-41e2-adb0-8bfdadaa9459.png)

**Comment by jfcisco** [comment]
I think the code that needs to change is this part: https://github.com/graphql/graphql.github.io/blob/48a374a702262f4e08e71de269466777d86130fb/src/components/Marked/swapiSchema.tsx#L383-L393

Like, the line `return info.schema.getType('Human');` should be `return 'Human';` instead

Similar changes are needed for lines 467 to 480

**Comment by XtofX** [comment]
this looks to be the change that introduced the issue:
https://github.com/graphql/graphql.github.io/pull/1293/files

**Comment by isConic** [comment]
Getting the same error when visiting https://graphql.org/learn/queries/

---  

![image](https://user-images.githubusercontent.com/48657113/202245156-c96b48f8-b2a6-4fac-a247-fcaac053d8a8.png)
---  

I chose the wrong day to learn graphql 😂

**Comment by Urigo** [comment]
That was my bad!
Rushed to update graphql-js to latest....

Thanks everyone for reporting
Solved thanks to @patrick91 in https://github.com/graphql/graphql.github.io/pull/1312
