### ISSUE TITLE
Add Ballerina language to the Code page

### ISSUE THREAD

**Issue by pubudu91** [graphql/graphql.github.io#1317]
### Description

Ballerina language's standard library provides a package for GraphQL which can be used for developing GraphQL APIs. It also includes a GraphQL client for interacting with GraphQL endpoints. It would be great if we can list Ballerina as well in the Code page of the site so that people looking for GraphQL libraries/tools will know that this is another option for GraphQL that they can look at.

**Comment by Urigo** [comment]
this was added, thank @pubudu91 !
