### ISSUE TITLE
Cant access `graphql.org/docs/introspection`

### ISSUE THREAD

**Issue by lpalmes** [graphql/graphql.github.io#133]
It seems that it escapes the js script when trying to access [introspection](http://graphql.org/docs/introspection/)

It respond with this piece as html escaped text
```
var React = require('react') var Redirect = require('../../_core/Redirect') export default () =>
```

**Comment by j0k3r** [comment]
Because there is nothing more :trollface: 
https://github.com/graphql/graphql.github.io/blob/source/site/docs/introspection/index.html

It should be a `.html.js`
