### ISSUE TITLE
"according to the GraphQL spec" points to a wrong url

### ISSUE THREAD

**Issue by CSalih** [graphql/graphql.github.io#1331]
### Description

The anchor link "[according to the GraphQL spec](https://github.com/graphql/graphql.github.io/blob/458c386a55566aa23c68ba99d30344b63ed65032/src/content/learn/BestPractice-ServingOverHTTP.md?plain=1#L72)" points to `http://facebook.github.io/graphql/#sec-Data` but this page does not exists anymore.

### Steps to Reproduce

1. Go to: https://graphql.org/learn/serving-over-http/#response
2. Click on `according to the GraphQL spec`

### Expected Result 

The page should be shown

### Actual Result 

The page will not be shown (Status code 404)

**Comment by Urigo** [comment]
thanks! could you submit a PR with a fix?

**Comment by CSalih** [comment]
Hi @Urigo, i prepared a PR with a fix for this page. 
I found a another broken GraphQL link in a blog post (https://github.com/graphql/graphql.github.io/blob/source/src/content/blog/2015-09-14-graphql.md) should i fix this as well? I can create another PR for the second broken link or put it into #1410.

**Comment by Urigo** [comment]
@CSalih thank you!
Just merged, can you please open a new PR with the other fixes?
Thanks!
