### ISSUE TITLE
List public GraphQL APIs on website

### ISSUE THREAD

**Issue by kwi-dk** [graphql/graphql.github.io#136]
... aka "enough about Star Wars". ;-)

I want to know about real-world GraphQL APIs, which can hopefully inspire my own API design and demonstrate best practices.

Facebook, and indeed most of the companies on the "Who’s using GraphQL?" page, seem to only use it internally, and that's great for them but doesn't really teach me anything. GitHub has a [publicly documented](https://developer.github.com/early-access/graphql) API. Are there others? 

If so, it might be helpful to separate that page into "companies with public APIs" (and link to API docs) and "companies using it internally".

**Comment by leebyron** [comment]
As far as I'm aware, Github is the current brave company to make their GraphQL API public. It's probably a bit silly to have a list of one thing on the site - but if there are others out there I'm happy to entertain a pull request to add such a section!!!
