### ISSUE TITLE
learn pages become blank after a moment

### ISSUE THREAD

**Issue by bufferings** [graphql/graphql.github.io#1400]
### Description

When I open https://graphql.org/learn/introspection/ page, it shows the page at the beginning, but it becomes blank after a moment.

### Steps to Reproduce

open the https://graphql.org/learn/introspection/ page

### Expected Result 

The page doesn't become blank

### Actual Result 

it shows white page

### Additional Context

My browser is Chrome Version 111.0.5563.146 (Official Build) (arm64) on MacOS
I also checked it with my Android Chrome browser and it shows the same result.

**Comment by bufferings** [comment]
It doesn't seem only introspection page, but also all the learn pages (except for the learn top page), which I could read a few hours ago.

**Comment by dannyhw** [comment]
Also have this issue on https://graphql.org/learn/queries/ 

tried running it locally and this seems to be the cause
```
Error in function QueryEditor.componentDidMount in ./src/components/Marked/MiniGraphiQL.tsx:143
codemirror__WEBPACK_IMPORTED_MODULE_6__ is not a function
```

I guess anywhere the editor (codemirror) is being used it will crash
