### ISSUE TITLE
Getting 404 on /swapi-graphql

### ISSUE THREAD

**Issue by henryqdineen** [graphql/graphql.github.io#1427]
### Description

I'm getting a 404 on the https://graphql.org/swapi-graphql route. I have definitely gone to this route in the past but it is no longer working. The reverse proxying doesn't seem to be working.

https://github.com/graphql/graphql.github.io/blob/7d5374d5fc9c8085652efa240c92ede4f2423641/static/_redirects#L4-L5

**Comment by johannes-vdm** [comment]
Looking into this

**Comment by acao** [comment]
hey @johannes-vdm - I originally added those redirect lines for netlify, let me know if there's anything I can help with!

this is a widely used legacy route, the original canonical graphiql demo referenced in many books and training modules, so we should at least 301 redirect it if we can no longer serve it from this path

**Comment by acao** [comment]
good news - we can solve this problem programmatically!
