### ISSUE TITLE
Adding "Brangr" client/browser to the Code page?

### ISSUE THREAD

**Issue by networkimprov** [graphql/graphql.github.io#1468]
Hi, many thanks for this wonderful website!

I'd like to submit a new open source app[1] to the code page. I found this guide:
https://github.com/graphql/graphql.github.io/blob/source/notes/ContributingToCodePage.md

Does that apply to anyone (e.g. me)? Do I simply create a PR with the content described therein? Anything else I need to know?

[1] https://github.com/networkimprov/brangr

**Comment by networkimprov** [comment]
cc @Urigo

**Comment by Urigo** [comment]
@networkimprov yes go ahead!

**Comment by networkimprov** [comment]
@Urigo, added in #1473 :-)

**Comment by jorydotcom** [comment]
Closed by #1473, with thanks to @networkimprov !
