### ISSUE TITLE
Edit this page button takes to github.com and to this repo

### ISSUE THREAD

**Issue by abhiraj-ku** [graphql/graphql.github.io#1491]
### Description

When I click on the "edit this page " on grahql.org homepage then it take me to github.com 

### Steps to Reproduce

click on the edit this page on https://graphql.org

### Expected Result

I Expected that this link would take me to this repo 
 
https://github.com/graphql/graphql.github.io

**Comment by jorydotcom** [comment]
Nice catch, can you open a PR to fix @abhiraj-ku?

**Comment by abhiraj-ku** [comment]
@jorydotcom yes, sure

**Comment by Urigo** [comment]
I think this is fixed now thanks to @dimaMachina's refactoring!
Please reopen if that's not the case
