### ISSUE TITLE
"Edit this page" link on FAQ page goes to `github.com/faq`

### ISSUE THREAD

**Issue by abhiraj-ku** [graphql/graphql.github.io#1515]
If we click on edit this page on graphql/faq then it takes to github.com/faq and not github.com/graphql/faq

**Comment by benjie** [comment]
(Moving to graphql.github.io repo.)

Specifically when you go to https://graphql.org/faq/ and click the `Edit this page` link in the footer, you are sent to `https://github.com/faq`.

Instead you should be sent to:

```
https://github.com/graphql/graphql.github.io/blob/source/src/pages/faq.tsx
```

Or, more ideally, to:

```
https://github.com/graphql/graphql.github.io/tree/source/src/content/faq
```

**Comment by Urigo** [comment]
I think this is fixed now thanks to @dimaMachina's refactoring!
Please reopen if that's not the case
