### ISSUE TITLE
Feature request for GitHub GraphQL?

### ISSUE THREAD

**Issue by michaelconan** [graphql/graphql.github.io#1603]
Is this the right repository for a feature request for the API itself?

**Feature:** `UpdateProjectV2Field` mutation

**Purpose:** Edit details or values of `ProjectV2Field`s, including `ProjectV2IterationField`, `ProjectV2SingleSelectField`, etc

**Example use case:** Recurring GitHub action workflow to create new iteration (sprint) in my V2 project

**Comment by benjie** [comment]
Sorry this is not the right place to ask about adding features to the GitHub GraphQL API, this is about GraphQL the technology. Please try a GitHub contact point, perhaps https://github.com/community
