### ISSUE TITLE
npm and GitHub stars/downloads show as 0 for all tools

### ISSUE THREAD

**Issue by meenakshi-dhanani** [graphql/graphql.github.io#1605]
### Steps to Reproduce
1. Browse https://graphql.org/code/#generic-tools

### Expected Result
I expected a number besides 0 for npm downloads or GitHub stars that the projects listed have. 

### Actual Result
<img width="1503" alt="Screenshot 2024-01-11 at 6 25 50 PM" src="https://github.com/graphql/graphql.github.io/assets/14279061/a4da6e19-6868-490d-af55-adb71aa97868">

**Comment by Urigo** [comment]
thanks for the heads up @meenakshi-dhanani !
it was because of the migration to Vercel, fixed now!
