### ISSUE TITLE
Add link to store.graphql.org

### ISSUE THREAD

**Issue by jorydotcom** [graphql/graphql.github.io#1606]
We would like to add a link to store.graphql.org to make it more discoverable, probably in the footer and/or community section?

**Comment by Urigo** [comment]
@jorydotcom @SeanGallen want to also add it to the new community section?

**Comment by SeanGallen** [comment]
Hi @Urigo, 
I am open to taking a look but where exactly would you want it?  At first look, I was thinking the [Essential Links](https://graphql.org/community/contribute/essential-links/) but please let me know if am I way off? Thanks

**Comment by Urigo** [comment]
maybe actually under [official channels](https://graphql.org/community/resources/official-channels/)?

**Comment by SeanGallen** [comment]
ok, I will check it out, this weekend. Thanks.

**Comment by SeanGallen** [comment]
@jorydotcom, can we close this issue or is there still work to be done?

**Comment by saihaj** [comment]
Thanks @SeanGallen!
