### ISSUE TITLE
Updated docs to reflect express-graphql deprecation

### ISSUE THREAD

**Issue by pTinosq** [graphql/graphql.github.io#1607]
### Description

I wanted to follow the tutorial on [Running an Express GraphQL Server](https://graphql.org/graphql-js/running-an-express-graphql-server/) on the official graphql.org website and found that the `express-graphql` library has been deprecated and replaced with the `graphql-http` library.

It would be nice to see an updated version of this tutorial created by the GraphQL foundation. (specifically for Express.js)

### Steps to Reproduce

Head over to [https://graphql.org/graphql-js/running-an-express-graphql-server](https://graphql.org/graphql-js/running-an-express-graphql-server) and the whole tutorial uses the deprecated `express-graphql` library

### Expected Result

A tutorial on how to quickly get up and running on express.js with the `graphql-http` library.

### Actual Result

An outdated tutorial that uses a deprecated library.

### Additional Context

The [GraphQL Foundation adopts graphql-http](https://graphql.org/blog/2022-11-07-graphql-foundation-graphql-http/) blog post was written over a year ago and the tutorial is yet to be updated!

**Comment by benjie** [comment]
@enisdenjo Maybe one of your existing examples would be straightforward to port over?

**Comment by enisdenjo** [comment]
Check out #1616!

**Comment by pTinosq** [comment]
Fantastic stuff... thanks for this!
