### ISSUE TITLE
window.opener phishing vulnerability

### ISSUE THREAD

**Issue by MAOliver** [graphql/graphql.github.io#162]
I had the graphql.org site up and opened this article "[Why I believe graphql will come to replace rest](https://dev.to/reactiveconf/why-i-believe-graphql-will-come-to-replace-rest)". The dev.to page redirected my graphql.org tab to [https://dev.to/phishing](https://dev.to/phishing).

**Comment by MAOliver** [comment]
The graphql site still contains a bunch of target="_blank" links (source of the vulnerability), but dev.to appears to no longer be "warning" against it.

**Comment by leebyron** [comment]
Thanks for the report - is this the best description of the vulnerability or do you have a better one? https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by MAOliver** [comment]
That seems right. I don't have any better examples.
