### ISSUE TITLE
Landscape iframe busted on https://graphql.org/users/

### ISSUE THREAD

**Issue by jorydotcom** [graphql/graphql.github.io#1627]
I think this is the same issue we had on the Members page in #1621; @YassinEldeeb do you mind taking a look?

**Comment by YassinEldeeb** [comment]
Sure! We're about to land our Next.js migration PR, so to not introduce more conflicts, I'm tagging @dimaMachina to confirm this is fixed within the #1604 PR.

**Comment by Urigo** [comment]
I think this is fixed now thanks to @dimaMachina's refactoring!
Please reopen if that's not the case
