### ISSUE TITLE
Add link to GraphiQL in Object Types tutorial

### ISSUE THREAD

**Issue by adamosimpson21** [graphql/graphql.github.io#1693]
If you run this code with node server.js and browse to http://localhost:4000/graphql you can try out these APIs with GraphiQL.

At the bottom of the Object types tutorial there's a small typo, GraphiQL should be GraphQL

**Comment by thistlehouse** [comment]
isn't the GraphiQL the interface (ide) where you run your queries?

**Comment by adamosimpson21** [comment]
oh? I didn't realize it was a separate technology. Maybe this should be updated with a link to that if it's something separate. Going over it as a first timer I just assumed it was a typo. Is this the best link to send someone to who wants to learn about it? https://github.com/graphql/graphiql/tree/main

**Comment by thistlehouse** [comment]
I landed here first [graphql](https://graphql.org/). Since I write in C#, I'm using https://github.com/ChilliCream/graphql-platform
