### ISSUE TITLE
I would like to sign the EasyCLA agreement

### ISSUE THREAD

**Issue by adamosimpson21** [graphql/graphql.github.io#1694]
title

**Comment by benjie** [comment]
Hi Adam: you can raise a PR here to test EasyCLA is working for you: https://github.com/graphql/easycla

**Comment by adamosimpson21** [comment]
Sorry, this still isn't working, I'm getting a 403 error again in the console for that repo, too.

**Comment by benjie** [comment]
I do not understand, what console? Please follow these steps; if at any point GitHub asks you to create a fork please do so:

1. Log in to GitHub.
2. Visit https://github.com/graphql/EasyCLA/blob/main/README.md
3. Click the pen icon at the top right ("Edit this file")
4. Add the word "testing" to the bottom of the README
5. Click the green button at the top right ("Commit changes..." or "Propose changes")
6. I advise that you do so via a branch. The branch name is unimportant, "testing" or similar is fine.
7. Raise a pull request with these changes ("propose changes"?)

**Comment by adamosimpson21** [comment]
oh, I see. Sorry I was pulling and pushing on my local machine, but this makes sense for small changes

**Comment by benjie** [comment]
Oh were you trying to push directly to the main repository? Very few people can do that, the normal way of contributing in open source projects on GitHub is to fork the repository and push your changes to your fork, then raise a pull request from your fork to the origin.
