### ISSUE TITLE
Feedback for “Introspection”: case-sensitivity of introspection fields?

### ISSUE THREAD

**Issue by akgerber** [graphql/graphql.github.io#1719]
My reading of the GraphQL specification is that all field names, including those reserved for introspection, are case-sensitive:
https://spec.graphql.org/October2021/#sel-EAFNZDPAACRAwnF

If that is correct, the documentation for the introspection fields should write them in lowercase as is done in the examples.

Uppercase:
![image](https://github.com/graphql/graphql.github.io/assets/201313/ce661068-74a1-47f5-b277-69acb8c863b5)
Lowercase:
![image](https://github.com/graphql/graphql.github.io/assets/201313/b2fccee6-6d46-47e6-acba-b772aa5d3fa3)

If my reading of the specification is incorrect, explicitly documenting that introspection fields are case-insensitive would be helpful.

**Comment by benjie** [comment]
Hi @akgerber; you're correct that the introspection _fields_ are in lower camelCase and are case sensitive (type names are also case sensitive). The part of the documentation you highlight here are not introspection _fields_, they are introspection _types_. I hope this helps!

**Comment by akgerber** [comment]
Thank you for that explanation! I see, one requests the `__schema` field of type Query and receives a response of type `__Schema`, as defined here in the specification?
https://spec.graphql.org/October2021/#sec-The-__Schema-Type

I personally would find such detail on the Introspection page helpful to better understand how types & fields work in the introspection context.

**Comment by Urigo** [comment]
@akgerber maybe you can create a PR for the docs in a way that you think would make it clearer for you and others?
