### ISSUE TITLE
Interest for a codegen blog post?

### ISSUE THREAD

**Issue by martinbonnin** [graphql/graphql.github.io#1760]
Hi everyone 👋 

Martin from [Apollo Kotlin](https://github.com/apollographql/apollo-kotlin) here. 

A question that's coming up quite often from our users is how come the codegen doesn't model classes after the GraphQL types but rather after the operations. 

The reason is type safety of course (cannot access the fields you did not query) but given that GraphQL and a lot of other type systems are so similar, expecting the same shapes seems like a pretty reasonnable expectation to have.

I'd love to write a blog post explaining the different ways to look at codegen and the various tradeoffs there so that I could point users at. 

Content would be cross-platform. Probably use TS for codeblocks examples but frame the content as cross platform enough so that it could apply to Swift/Kotlin developers as well.

Is that something that could belong to graphql.org? Any interest in this?

**Comment by benjie** [comment]
Absolutely; I'm sure we'd love to see this! I've come across the exact same confusion. Please go ahead, and let me know if you need any guidance or input.

**Comment by benjie** [comment]
cc @jorydotcom

**Comment by AnthonyMDev** [comment]
[My talk at GraphQL Conf](https://graphql.org/conf/2024/schedule/c9734088ee56ff8e1410bf33e494f71d/?name=Consuming%20GraphQL%20in%20Type-Safe%20Languages) is going to be about this same topic.

We could pair the talk as a companion to this post?

**Comment by martinbonnin** [comment]
Draft [here](https://docs.google.com/document/d/1FRFsOQg9QzLMFER5nVZkHpbnpDjNL4c9S1oQNGmaPio/edit?usp=sharing), comments welcome!

**Comment by martinbonnin** [comment]
Any other feedbacks? What's the typical process here? Should I move the contents to https://github.com/graphql/graphql.github.io/tree/source/src/pages? Or something else?

**Comment by benjie** [comment]
Hey! Sorry, GraphQLConf ate all my time for the last month. Your blog post reads well; I've made a number of suggested edits for you to consider, some minor typo/grammar, and some more structural. Let me know what you think! Once accepted/rejected, we should indeed move the blog post into the website tree, like in #1731

**Comment by martinbonnin** [comment]
No worries at all, hope GraphQL conf was a blast! One small comment remaining and I'll move that to a draft.

**Comment by martinbonnin** [comment]
Thanks all for the feedbacks, I moved the post to GitHub [here](https://github.com/graphql/graphql.github.io/pull/1778)

**Comment by benjie** [comment]
:raised_hands:  Closing in favour of https://github.com/graphql/graphql.github.io/pull/1778
