### ISSUE TITLE
Feedback for “Pagination”

### ISSUE THREAD

**Issue by rfu-lt** [graphql/graphql.github.io#1761]
Hi, I am reading
https://graphql.org/learn/pagination/

I have a question, what is the reason to provide `cursor` for every element in the response, considering we have page info separately.
![image](https://github.com/user-attachments/assets/5683cc23-82b6-4aa1-9c61-f1ff12adc023)

**Comment by benjie** [comment]
Imagine you're paginating four items at a time (`first: 4`). First page you get cursors `c1`, `c2`, `c3`, `c4`. You paginate forward and get `c5`, `c6`, `c7`, `c8`. You then perform a mutation which creates cursor `c6.5` in the middle of this page. We only want to show 4 items, so you choose to render `c6`, `c6.5`, `c7`, `c8`. You paginate backwards; now you need `before: "c6"`. If you hadn't requested the cursor on each edge and just got the start/end cursor, you wouldn't know what `c6` was.

**Comment by rfu-lt** [comment]
Oh. That makes sense. Thanks for the explain

**Comment by benjie** [comment]
You're welcome!

**Comment by Urigo** [comment]
@rfu-lt do you think we should add some notes to the docs that would benefits others?

**Comment by rfu-lt** [comment]
hi @Urigo  

when I first read the doc, I wasn't thinking about the `traverse back` case. That is a good callout.

Essentially, we are suggesting `providing a cursor for every element so that you can start paginated-query from any element , to any direction, at any time (e.g. after inserting elements)`.
^ this suggestion make sense to me (though it all depends on the feasibility of underline implementation details). So I feel it would be great if we can add some notes to explain the use-cases as well as the the intentions behind the design.

Well, with this, the `endCursor` in the `pageInfo` could be a dup info.

As long as reader understand the use-cases/intentions, readers can make decisions. Thanks for writing up this doc.

**Comment by Urigo** [comment]
@rfu-lt would you be interested in offering a PR to the docs with the content you think would best fit?
