### ISSUE TITLE
Found broken `/schema` link. Please fix!

### ISSUE THREAD

**Issue by Maxiwere45** [graphql/graphql.github.io#1805]
https://graphql.org/schema/
![image](https://github.com/user-attachments/assets/70c02968-3c6a-47f6-ab57-8a504509c575)

**Comment by benjie** [comment]
On which page did you find the broken link?

**Comment by Maxiwere45** [comment]
Over here : 
![image](https://github.com/user-attachments/assets/e78e997c-0bef-466b-bf29-25d9595e92d9)

**Comment by benjie** [comment]
Thanks!
