### ISSUE TITLE
Pagination alternative

### ISSUE THREAD

**Issue by morris** [graphql/graphql.github.io#240]
Merry christmas everyone 🎁 

Here's an alternative to the recommended approach regarding pagination.

```graphql
type Query {
  allPeople(first: Int = 0, after: String = ""): [Person]
  allPeoplePage: PageInfo!
}

type PageInfo {
  nextCursor: String
  prevCursor: String
  startCursor: String
  endCursor: String
  cursors: [String]
  totalCount: Int
}
```

The idea is a basic convention: Any list field `x` may have pagination info at `xPage`. `hasNextPage/hasPrevPage` would be `nextCursor/prevCursor !== null`, respectively.
`cursors` would hold a list of cursors aligned to the returned items.

Pros:

- Much less types. For example, no `PersonConnection`, no `PersonEdge`, etc.
- Data structure is not dictated by "has to support pagination (or not)"
- Orthogonal: We can evolve from "pagination for x not supported" to "x can now be paginated by requesting xPage" without breaking x or introducing "pagedX { edges: { node: { name } } pageInfo: { ... } }"
- Shallow data is easier to consume

Cons:

- Cannot add edge-specific information like "friendship time". You'll have to introduce a "Friendship" thing in that case anyway, though.
- Data-wise, `cursors` are only indirectly coupled with their items (by index)

What do you think? If it could be useful to the community, I'd be happy to write it up for graphql.org. I'm looking to use this pattern next year and come back with real-world feedback.

Cheers

**Comment by asiandrummer** [comment]
Hi @morris - first of all thanks for the suggestion! There are some questions/issues that we were able to identify with this approach:

1. I presume that having an extra type to inquire for pagination information would require multiple resolvers (e.g. `field` and `fieldPageInfo`) to have access to the same data, probably treated as mutable. Not sure if this is officially disallowed, but at most this technique should be avoided as this can easily lead to complications, possibly even a race condition. Generally this screws up debugging/caching as well.

2. How would you deal with calling the pagination info for a field with multiple sets of args?
```
one: paginationField(first: 1)
two: paginationField(first: 2)
paginationFieldPageInfo {...} # for which field??
```
Maybe `cursors` field could resolve to the data structure that can help with this particular case, but it's difficult to see the value over the existing recommendation of using `Connection`s for pagination.

Having said this, we'd love to hear about the real-world tradeoffs if this pattern has been used anywhere in prod! For now it does sound like this pattern is an idea that you're trying to experiment with - we only write about best practices that have been used in prod for a while, so there are lessons learned to report on.

**Comment by morris** [comment]
Hi @asiandrummer, thanks for working through this.

1. Good point. I do think it's feasible (some strategy using promises/deferred resolution comes to mind) and worth the overhead if it simplifies the API and its evolution.
2. That's definitely a caveat. I'd go for:

```
one: paginationField(first: 1)
two: paginationField(first: 2)
onePageInfo: paginationFieldPageInfo {...}
twoPageInfo: paginationFieldPageInfo {...}
```

Should work, although certainly not ideal, as the resolvers now need to know about aliases, too.

Of course you're right - this can't become a best practice without hitting prod first. I'll come back to you with real-world experience in a while. Thanks again 🍻

**Comment by stubailo** [comment]
A fine alternative is:

```
type Query {
  allPeople(first: Int = 0, after: String = ""): PersonPage!
}

type PersonPage {
  people: [Person]
  nextCursor: String
  prevCursor: String
  startCursor: String
  endCursor: String
  cursors: [String]
  totalCount: Int
}
```

AFAIK this gives you some of the benefits of the connections with edges/nodes but without the extra vocabulary.

**Comment by hwillson** [comment]
Pagination with GraphQL has taken several twists and turns since this issue was opened. There are lots of [cursor connection spec](https://relay.dev/graphql/connections.htm) alternative approaches out there, and if anyone is up for expanding the current [pagination section](https://graphql.org/learn/pagination/) of the docs with battle tested alternatives, definitely let us know. We'll close this issue off for now though since it has been open for almost 6 years 😅. Thanks!
