### ISSUE TITLE
operationName is hard to grasp

### ISSUE THREAD

**Issue by martinheidegger** [graphql/graphql.github.io#241]
The current section about operation names, here: http://graphql.org/learn/queries/#operation-name
reads like this: 

> One thing we also saw in the example above is that our query has acquired an operation name. Up until now, we have been using a shorthand syntax where we omit both the query keyword and the query name, but in production apps it's useful to use these to make our code less ambiguous.
>
> Think of this just like a function name in your favorite programming language. For example, in JavaScript we can easily work only with anonymous functions, but when we give a function a name, it's easier to track it down, debug our code, and log when it's called. In the same way, GraphQL query and mutation names, along with fragment names, can be a useful debugging tool on the server side to identify different GraphQL requests.

The problem is that after reading this section there is no example or other hint on the shape in which the operation's name should be specified or where to look up the spec. It would be nice to be pointed to somewhere in this section.

Aside from that: Thank you for your great work!

**Comment by wincent** [comment]
> The problem is that after reading this section there is no example or other hint on the shape in which the operation's name should be specified or where to look up the spec. It would be nice to be pointed to somewhere in this section.

Good point, @martinheidegger. Would you like to submit a PR that adds a (probably small) example?

**Comment by stubailo** [comment]
I agree with this - that section introduces a lot of new concepts at the same time and should probably do that incrementally.

**Comment by martinheidegger** [comment]
@wincent Sorry, but I havn't figured out how it is supposed to work yet.

**Comment by stubailo** [comment]
Operation name is a "cosmetic" name for this particular query, much like a function name in JavaScript. So:

```graphql
{ me { username }}
```

Is like an anonymous function:

```js
() => { return 'hello' }
```

Here's a query with an operation name:

```graphql
query MeQuery {
  me { username }
}
```

That's like a named function:

```js
function getGreeting() {
  return 'hello';
}
```

Basically it's a string you can use to refer to that function in your code, developer tools, logs, stack traces etc.

**Comment by idibidiart** [comment]
@stubailo a funny thing I ran into just now that's confusing m noob brain:

when I don't use "query" as in "query { ... " and instead use just "{ ... " GraphiQL returns an error saying it "Unknown operation named \"null\"" 

If I use "query { ..." it works just fine, but if I then remove "query" and re-evaluate it works, too, but not after I refresh the GraphiQL page (then it requires 'query' qualifier again or it produces the aforementioned error.

I guess a bug in GraphiQL?

**Comment by wincent** [comment]
> I guess a bug in GraphiQL?

Sounds like it could be. If you can still repro on the latest release (0.9.1), please report it over [on the GraphiQL issues page](https://github.com/graphql/graphiql/issues).

**Comment by stubailo** [comment]
By the way, I wrote a post about this recently: https://dev-blog.apollodata.com/the-anatomy-of-a-graphql-query-6dffa9e9e747

If someone has time, please send some PRs to GraphQL.org with content lifted from that post!
