### ISSUE TITLE
Mention Scaphold.io on http://graphql.org/code/

### ISSUE THREAD

**Issue by Mitranim** [graphql/graphql.github.io#283]
https://scaphold.io looks like a fantastic BaaS dedicated to GraphQL. I only heard about it by accident. Be nice if the official docs suggested it.

**Comment by stubailo** [comment]
It doesn't fit well with the current content of that page, but it maybe could be reasonable to add a section with something like "GraphQL services"? I think there are like 5-6 services that would qualify.

**Comment by leebyron** [comment]
Would consider PRs adding this kind of section to that page!

Bonus points for a nice nav sidebar that helps people jump around on that page

**Comment by christiane-deneser** [comment]
Hi there,
can I work on that issue and add a nav sidebar to the page "Code"?

Would you consider dividing the page in three parts?: 
1. Servers 
2. Clients 
3. Tools & Services (including "More Stuff")?
In that way the wording in the footer nav is (more or less) matched.

Or would you prefer a fourth part for Services (including "More Stuff")?
In that way I would add another link "Services" to the footer nav as well.

Also, I could add a "continue reading" link at the end of each part. That way the page becomes more structured and easier to perceive as lots of content has accumulated over the past months.

I would be happy to help. Also, I am pretty new to contributing to OS and find that issue a nice way to start.

Best,
Christiane

**Comment by Mitranim** [comment]
Nevermind, the service went down.
