### ISSUE TITLE
Document default values for query variables

### ISSUE THREAD

**Issue by stubailo** [graphql/graphql.github.io#294]
Below this section in the docs: http://graphql.org/learn/queries/#variables

There should be a section about how to set default variables. You can see an example of how this works in @clayallsopp's great article, [GraphQL Tour: Variables](https://medium.com/the-graphqlhub/graphql-tour-variables-58c6abd10f56)

Could be a great first PR for somebody!

**Comment by SheW0lf** [comment]
I would like to work on this.

**Comment by localhostpedro** [comment]
@stubailo is there any more working on Documentation ? Specially translate to ptbr ?

**Comment by localhostpedro** [comment]
@stubailo is there any more working on Documentation ? Specially translate to ptbr ?
