### ISSUE TITLE
link rot http://graphql.org/users/

### ISSUE THREAD

**Issue by hanachin** [graphql/graphql.github.io#305]
The link [More GraphQL Users](http://graphql.org/users/) in http://graphql.org returns 404 error

**Comment by pm-dev** [comment]
Most likely due to: https://github.com/graphql/graphql.github.io/pull/304

**Comment by wincent** [comment]
With  bdf8894 this hopefully won't happen again.

**Comment by wincent** [comment]
Thanks for the report, @hanachin.
