### ISSUE TITLE
[documentation] Possibly incorrect example in pagination docs

### ISSUE THREAD

**Issue by npgall** [graphql/graphql.github.io#335]
I'm just getting familiar with GraphQL, so forgive me if I'm missing something. But I found the following snippet confusing in the documentation on [pagination](http://graphql.org/learn/pagination/#pagination-and-edges).

> _"our friends field should give us a list of edges, and an edge has both a cursor and the underlying node:"_

...but in the associated example, the GraphQL request does not mention edges:
```
{
  hero {
    name
    friends(first:2) {
      node {
        name
      }
      cursor
    }
  }
}
```

Should the example be something like this?:

```
{
  hero {
    name
    friends(first:2) {
      edges {
        node {
          name
        }
        cursor
      }
    }
  }
}
```

Btw many thanks for releasing this impressive library!

**Comment by wincent** [comment]
Great catch @npgall: it should indeed have the `edges` field in there. Would you like to submit a PR?

**Comment by npgall** [comment]
No problem I will create a PR. Thanks!

**Comment by npgall** [comment]
PR is above. Let me know if you need anything else. Thanks!

**Comment by wincent** [comment]
Thanks a bunch @npgall!
