### ISSUE TITLE
how to config algolia

### ISSUE THREAD

**Issue by willin** [graphql/graphql.github.io#342]
we forked this repo and translate it into chinese.

algolia has already setup.  index has been added. but cannot get search result.

is there anything must be config?

**Comment by wincent** [comment]
Best documentation I am aware of for configuring Algolia is [here](https://github.com/algolia/docsearch). You can also see in 9b62327a1741085d9c76f17759765a06bb3d444f how we initially set things up when search was first added. I would expect you'd need to do your own registration and obtain an API key etc to test this out.
