### ISSUE TITLE
Confused about how to merge fields in field selection

### ISSUE THREAD

**Issue by Peping** [graphql/graphql.github.io#375]
Currently the GrapgQL spec at https://facebook.github.io/graphql/#sec-Field-Selection-Merging only mention conditions that have to apply in order for fields in a selection to merge. While discussing a fix to an issue ( https://github.com/Youshido/GraphQL/issues/138 ) the specification was brought up. 

It is pretty confusing to infer how to actually merge fields in a selection just from the specs alone, because they only seem to be talking about **how to know when multiple fields can merge**, and not about **how to actually do the merging**.

Can we get some more specific documentation on how to merge fields? Can we get some examples of how to merge fields of object types and array types?

**Comment by stubailo** [comment]
I think this should be reposted at https://github.com/facebook/graphql, the repo for the spec!

Really good question though.
