### ISSUE TITLE
Figure out a schema for all query examples

### ISSUE THREAD

**Issue by stubailo** [graphql/graphql.github.io#38]
That way, we can set up all of the examples with the interactive query editor, instead of having static code snippets. But we need to make sure the schema has all of the features we want to demonstrate. Opening the issue here to keep track of this need.

**Comment by stubailo** [comment]
Going to do this after writing up the other section of "Learn", since we need a complete catalog of schema features necessary.

**Comment by stubailo** [comment]
Needs to have union types.

**Comment by stubailo** [comment]
@leebyron how do you feel about implementing the schema using the "model-style" code, where we just make a schema using the schema language, and then pass all of the args through to the default resolver? Right now there are a ton of comments with the schema language, and keeping those in sync with the actual implementation seems super tedious.

Just wanted to check in before making that change.

**Comment by leebyron** [comment]
Yeah I think that makes sense

**Comment by stubailo** [comment]
Note: Make an example of a non-nullable list

**Comment by leebyron** [comment]
I like your idea to use search results as a use for union types - it's actually a pretty good canonical case for when you would use union, modeling a heterogeneous list.

It probably wouldn't be too hard to make a ghetto search feature which returned Films based on title, Characters on name, Starships on model, etc.

**Comment by stubailo** [comment]
> I like your idea to use search results as a use for union types

Heh, I copied it from the spec :]

Agreed about the search feature in the schema. It could be implemented as a basic regex search.

**Comment by leebyron** [comment]
Haha nice. Thats probably thanks to Dan or Nick

**Comment by stubailo** [comment]
WIP: #44
