### ISSUE TITLE
GraphQL.org is not HTTPS

### ISSUE THREAD

**Issue by richard-hulm** [graphql/graphql.github.io#410]
https://graphql.org gives a security error as it's serving a github certificate

**Comment by j0k3r** [comment]
> HTTPS is not supported for GitHub Pages using custom domains.

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by richard-hulm** [comment]
If Github pages doesn't support it natively, you could always use a free service like CloudFare, or another proxying service that provides you with SSL?

**Comment by kachkaev** [comment]
Also curious if accessing `graphql.org` via https could be possible. I started using [https everywhere](https://addons.mozilla.org/en-GB/firefox/addon/https-everywhere/) in Firefox recently and `graphql.org` became unavailable.

**Comment by leebyron** [comment]
I'm going to investigate migrating from github pages to netlify which has much better SSL support.

**Comment by joshprice** [comment]
@leebyron Having recently moved a bunch of sites to Netlify I can confirm that the setup experience is pretty amazingly smooth. A+ would SSL again.

**Comment by fazouane-marouane** [comment]
Hi,

@leebyron did you find the time to test Netlify? It's seems to be pretty straightforward from their documentation as they support continuous deployment.

I took the liberty to [fork](https://github.com/fazouane-marouane/graphql.github.io) this very repository and deployed my fork on [Netlify](https://app.netlify.com/start) in a matter of seconds.
Here's a link to the deployed site: https://admiring-wozniak-2e11c7.netlify.com/
I also [tested Continuous deployment](https://github.com/fazouane-marouane/graphql.github.io/pull/1) and it works very well, they also support preview deploys, which is great!

**Comment by macsual** [comment]
[graphql.org](https://graphql.org/) is now accessible over HTTPS since the announcement that [custom domains on GitHub Pages have gained support for HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). However, "HTTPS enforcement" should now be [explicitly enabled](https://help.github.com/articles/securing-your-github-pages-site-with-https/) so that all HTTP requests to the website will automatically be upgraded to HTTPS.

**Comment by leebyron** [comment]
Fixed!
