### ISSUE TITLE
add mutation documentation to http://graphql.org/blog/rest-api-graphql-wrapper/

### ISSUE THREAD

**Issue by graingert** [graphql/graphql.github.io#430]
eg how to make POST requests.

**Comment by carolstran** [comment]
👋🏼 @graingert Thanks for opening an issue in the GraphQL docs! I know that it's been nearly 3 years, but I took a lot at the resource you mentioned. I don't think it makes sense to update a blog post, but rather make sure that the information you're looking for is available in the official docs. 

We have this [section on POST requests](https://graphql.org/learn/serving-over-http/#post-request), but I'd be curious to hear if you think there's more that should be added (there probably is) and where that information should live. Serving over HTTP? Mutations? Let me know what you think.
