### ISSUE TITLE
BSD or MIT

### ISSUE THREAD

**Issue by ashinzekene** [graphql/graphql.github.io#438]
I visited the website and to my surprise I saw this 

__Copyright ©2017 Facebook Inc. The contents of this page are licensed BSD-3-Clause.__

Graphql-js is MIT but when I read the docs I see as above. I almost submitted a PR but then I checked the graphql repo and found out some projects are licensed MIT while others are BSD.

Did you do it on purpose? I'm a little confused

**Comment by leebyron** [comment]
Projects have been moving to MIT on a case by case basis. @JoelMarcey, perhaps you could help us investigate this?

**Comment by JoelMarcey** [comment]
Hmmm.. many times the documentation for our projects are licensed as Creative Commons - e.g., https://github.com/facebook/Docusaurus/blob/master/LICENSE-docs

And we don't have that clause listed on the site.

Would the docs being CC be ok?

**Comment by oreno4649** [comment]
[The LICENSE file](https://github.com/graphql/graphql.github.io/blob/source/LICENSE) says that it is not BSD or MIT.
How is the actual document licensed?

**Comment by JoelMarcey** [comment]
@oreno4649 - Since this issue was originally raised, GraphQL has moved to the Linux foundation. I believe this should be licensed to MIT, and we just missed it, but I will let @leebyron or @caniszczyk make that call.

**Comment by caniszczyk** [comment]
MIT is fine

**Comment by oreno4649** [comment]
@JoelMarcey @caniszczyk Thank you for your reaction.

I make the PR. Please check the license notation.

**Comment by Urigo** [comment]
This can be closed, we are now MIT: https://github.com/graphql/graphql.github.io/pull/1104
