### ISSUE TITLE
printable docs

### ISSUE THREAD

**Issue by fsiler** [graphql/graphql.github.io#647]
Hello,
  I'd like to print myself a handbook, but the layout of the docs is making this somewhat difficult.  I forked and managed to get rid of the sidebar, but each section tag is limited to one page- so even if try to make a PDF of a really long page, I get exactly three pages: one for the header, one for the truncated body, and one for the footer.  Can someone please fix this?

Super feature request: one-page version of the docs.  For now, I'll just manually merge the markdown files.

**Comment by carolstran** [comment]
Thank you for the issue @fsiler!

Unfortunately, this issue isn't something that we feel will yield reward commensurate to the effort required to restructure the docs for this use case, so I’m going to label this a wontfix and close it out. However, a single-page version of the docs is something that we might consider merging should someone else be willing and interested in opening a PR to add.
