### ISSUE TITLE
API valueFromAST is missing

### ISSUE THREAD

**Issue by anhldbk** [graphql/graphql.github.io#685]
Hi there,

This section about GraphQL utitilities does NOT contain any information about `valueFromAST`: https://graphql.github.io/graphql-js/utilities/

Should I make a PR against this missing?

**Comment by carolstran** [comment]
👋🏼 @anhldbk, thanks for opening an issue on the GraphQL documentation! You're right, it seems that we have docs on [astFromValue](https://graphql.github.io/graphql-js/utilities/#astfromvalue) but not `valueFromAST`. I've never used it personally, but I could imagine it being a good addition.

@IvanGoncharov, what do you think?

**Comment by IvanGoncharov** [comment]
@anhldbk @carolstran `graphql-js` docs are a mess at the moment. It's my next goal to address it after TS conversion, tracked in https://github.com/graphql/graphql-js/issues/1368
