### ISSUE TITLE
graphql.org NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by legopin** [graphql/graphql.github.io#710]
After #709 was resolved, chrome browser (MacOS Version 74.0.3729.169 (Official Build) (64-bit))
shows certificate invalid warning about "NET::ERR_CERT_COMMON_NAME_INVALID"

<img width="1164" alt="Screen Shot 2019-05-30 at 3 44 05 PM" src="https://user-images.githubusercontent.com/15863509/58617221-2a9adf00-82f2-11e9-973b-dda6e42ebe9d.png">
<img width="1164" alt="Screen Shot 2019-05-30 at 3 44 48 PM" src="https://user-images.githubusercontent.com/15863509/58617224-2bcc0c00-82f2-11e9-8d39-6f22a7afafed.png">

**Comment by lucperkins** [comment]
Sadly, these hiccups are pretty much inevitable when you switch DNS *and* migrate to a Let's Encrypt cert at the same time. This should be all fixed now, and permanently so. I'm closing this, but please re-open if issues persist.
