### ISSUE TITLE
Is the source code for the example used in /learn available? 

### ISSUE THREAD

**Issue by hacker-DOM** [graphql/graphql.github.io#728]
I feel like the `/learn` section is a bit all over the place. It starts with Queries and Mutations, but there are more links from this chapter to Schemas and Types than vice versa. Maybe swap the order of the two chapters? In any case, I'd love a canonical source code for the tutorial - is that available? Cheers

**Comment by dteiml** [comment]
Went here to look if anyone has asked this q and turns out I have a few weeks back. It's still relevant: Where can I find the source code for the tutorial? Cheers

**Comment by skedwards88** [comment]
I thought the interactive code blocks were pretty nice, so I poked around to learn some more. The `MiniGraphiQL` component [here](https://github.com/graphql/graphql.github.io/blob/739a1c913fa4a88ac7c64c93ce68fc64ec0cbd96/site/_core/MiniGraphiQL.js) may be what you are looking for @hacker-DOM .

**Comment by ericz1803** [comment]
I was looking for the same thing and I found the file containing the schema and resolvers [here](https://github.com/graphql/graphql.github.io/blob/739a1c913fa4a88ac7c64c93ce68fc64ec0cbd96/site/_core/swapiSchema.js).

**Comment by carolstran** [comment]
👋🏼 @hacker-DOM, thanks for opening an issue on the GraphQL documentation! From what I can tell, the links that the others provided address what you're asking about - so I'm going to close this issue. If I misunderstood or something is still unclear, please let me know.
