### ISSUE TITLE
Code page re-design idea

### ISSUE THREAD

**Issue by orta** [graphql/graphql.github.io#768]
I heard on the Microsoft grapevine that there was interest in a general GraphQL site redesign, and maybe the code page could be a good place to start. 

So... I took a quick stab at the page, trying to chunk it into a horizontal set of navigations which are mostly icon based, then tried to provide a more structured way to describe each dependency. Left is what it is, right is how to use it. Each "how to use it" can have a max height which is expandable to make it easy to scan the whole page but dig in on a specific thing you have interest in. This makes it possible to look at a bunch then compare different tech in the same language

[current page](https://graphql.org/code/)
![Artboard](https://user-images.githubusercontent.com/49038/64985468-e9bfd980-d892-11e9-8c22-036e7c49d116.png)

**Comment by orta** [comment]
It's been a month, maybe the right answer is for me to bring this up at the GraphQL Working Group and get something started a bit like what we did with GraphiQL?

**Comment by rabeehrz** [comment]
Hey @orta ,

I would like to contribute to GraphQL website and make it better. This redesign looks really cool. Is it something you have plans to implement? Has your team decided on this? 

Would love to get details. Thanks

**Comment by elit-altum** [comment]
Hey @orta 
This looks great. I'd also like to work on it if it is approved for implementation. Could you please keep me in the loop? Thank you!

**Comment by Siddhant043** [comment]
Hi @orta  
The new design is amazing 🤩 and I would love to contribute to GraphQL website.
Thank you 😊

**Comment by Urigo** [comment]
Love this suggestion and we would love to help.

One big question I had was - who decides on which libraries to merge in and how do we order those tools?

Initial suggestion would be - Creating a standard using something like - (Github stars, Commit volume, Latest commit which is not renovate/bot) and use this standard to both decide if to include a library or not (or even remove) and to order the already included libraries.

Is there a working group or somewhere we could move those discussions forward?

**Comment by carolstran** [comment]
@Urigo, that's a great question and something that I'm really wondering about too - especially since a majority of the open PRs and issues are related to contributions to the Code and Community pages. Any insights on this @orta @IvanGoncharov?

We can also move this discussion out to a separate issue as to not clog up the design discussion. Which PS. I really like this design and I'd support it moving forward 💓

**Comment by IvanGoncharov** [comment]
@carolstran I propose to return to this issue after Gatsby's conversion.

**Comment by Urigo** [comment]
We now have an open PR for this change, please give your thoughts and reviews there as well:  https://github.com/graphql/graphql.github.io/pull/936

**Comment by orta** [comment]
This is live!
