### ISSUE TITLE
Update react-version

### ISSUE THREAD

**Issue by rajkharvar** [graphql/graphql.github.io#776]
All the routes from https://graphql.org/learn/ are having outdated version of react. Please update it to the latest version.

**Comment by georgioupanayiotis** [comment]
Hi @rajkharvar , 
Do you mean react version on package.json ?

**Comment by rajkharvar** [comment]
yes. react-dev-tools recommend updating to the latest version of react to avoid a nightmare.

**Comment by snitin315** [comment]
@rajkharvar can I work on this issue?

**Comment by carolstran** [comment]
👋🏼 Thanks for this issue! I commented on the associated PR, but I'll drop a similar message here to keep the discussion in sync.

While I agree that this would be necessary for the existing site, the React version will be updated with the migration to Gatsby (#896) which is already on the roadmap. So I'm going to close this for now, but if you have any concerns or think I'm mistaken - let me know!
