### ISSUE TITLE
extend input type with alias name

### ISSUE THREAD

**Issue by veeramarni** [graphql/graphql.github.io#778]
I'm would like to request the following idea to be added to a spec.

```
input BaseInput {
  stars: Int!
}

extend input BaseInput as ReviewInput {
  commentary: String
}

```

So that I can use one of the input `BaseInput` or `ReviewInput` based on the need. And not extending `BaseInput` directly.

**Comment by carolstran** [comment]
👋🏼 @veeramarni, thanks for opening an issue on the GraphQL documentation! However, after reading, it seems like this is an issue that would be better for the [graphql-spec](https://github.com/graphql/graphql-spec/issues) repo.

I'll close this for now, but if I've misunderstood - please let me know!
