### ISSUE TITLE
Bring License in line with graphql-spec

### ISSUE THREAD

**Issue by orta** [graphql/graphql.github.io#823]
/cc @leebyron  / @jchris who should probably decide

Based on this comment by @IvanGoncharov  https://github.com/graphql/graphql-js/pull/1960#issuecomment-500565005 

It looks like this repo should go MIT for consistency, if so we can merge https://github.com/graphql/graphql.github.io/pull/703 now - if no responses I'll give it a merge in 3 months (chance for anyone to give feedback), as I think it's the right thing to do 👍

**Comment by carolstran** [comment]
Left a review on #703 and referenced this issue - it'd be great to get that merged if possible 🚀

**Comment by IvanGoncharov** [comment]
@carolstran @orta I started the relicensing process with GraphQL Foundation.
Can take some time since we need conformation from FB as previous copyright owners, will keep you updated.

**Comment by Urigo** [comment]
We can close this as this repo is now MIT
