### ISSUE TITLE
search bar error

### ISSUE THREAD

**Issue by Arraxx** [graphql/graphql.github.io#831]
### Screenshot:
![Screenshot from 2020-02-21 19-10-54](https://user-images.githubusercontent.com/54955755/75039266-5001f580-54de-11ea-952d-5e7a4c0cafaf.png)

### Additional context
if really a bug,i would like to take this up.

**Comment by coderbabu10** [comment]
@orta

**Comment by orta** [comment]
Sure, it looks like a real bug - you're welcome to submit a fix

**Comment by ani4aniket** [comment]
@orta May I take this issue, I guess @coderbabu10 is not working on it yet.

**Comment by git-anurag-hub** [comment]
AnyOne, Working on this issue?

**Comment by ardatan** [comment]
I think this has been fixed after Gatsby migration;
https://github.com/graphql/graphql.github.io/pull/938/commits/048322edf548a15f566c34d5a2113cd2e9f6ed96

**Comment by Urigo** [comment]
I believe this is fixed on the new website, please reopen if that's not the case
