### ISSUE TITLE
navbar error

### ISSUE THREAD

**Issue by Amankumar29** [graphql/graphql.github.io#832]
### Screenshot:
![Screenshot from 2020-02-21 22-28-28](https://user-images.githubusercontent.com/54955755/75054780-bd6f4f80-54f9-11ea-8d38-9c603af063d6.png)

### Additional context 
I would like to take this issue

**Comment by coderbabu10** [comment]
@orta

**Comment by RoLoDeXx** [comment]
https://github.com/graphql/graphql.github.io/pull/837 
I've made a PR for this.

**Comment by carolstran** [comment]
Closing as this was resolved in #839 🚀
