### ISSUE TITLE
Feature: issue and pull request templates

### ISSUE THREAD

**Issue by godcrampy** [graphql/graphql.github.io#834]
Currently there are no templates for creating PRs and issues.
From github [docs](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates):
>  With issue and pull request templates, you can customize and standardize the information you'd like contributors to include when they open issues and pull requests in your repository.

This will help in better maintenance and communication especially since there will be a lot of incoming PRs as graphql is on the GSoC list.

**Comment by carolstran** [comment]
👋🏼 @godcrampy, thanks for opening this issue! I would agree, typically I find the experience of contributing to repos with templates for issues and pull requests is a better experience.

Ping @IvanGoncharov @orta - Is there a process for implementing something like this? Or could someone propose a change via PR? It'd be great to sort this out before Hacktoberfest 🎃

**Comment by IvanGoncharov** [comment]
@carolstran Definitely something we need to address before Hacktoberfest.
We can start from something super simple, can you please look at what other similar repositories (website for popular OSS technologies) have?

**Comment by carolstran** [comment]
@IvanGoncharov Yup, totally agree on getting something simple up and then figuring out our needs as more PRs/issues come in. I'll take a look at other projects and open a PR by the end of the week 💫
