### ISSUE TITLE
Too many iFrameResizer console logs 

### ISSUE THREAD

**Issue by elit-altum** [graphql/graphql.github.io#838]
__Issue__
The iFrameResizer at https://graphql.org/users/ logs every communication between the files in use which results in >120 logs on the console. This can potentially effect the website response and load time on many slower browsers.
They might be useful in development environment but should be hidden for production.

__ScreenShots__
![IFrameError](https://user-images.githubusercontent.com/41413622/75107312-907c8300-5646-11ea-8369-fc0810764dbf.gif)

__Potential-Fix__
We can use the 
```
iFrameResizer({log: false})
```
attribute to fix this.

I would like to work and fix this issue.

**Comment by carolstran** [comment]
👋🏼 @elit-altum, thanks for opening this issue! I can't seem to reproduce these logs... is it still happening for you?

**Comment by elit-altum** [comment]
Nope I can't see them anymore. Don't know what fixed it.

Closing this issue.
Thank You!
