### ISSUE TITLE
Replace Sangria by Caliban (Scala graphql implementation)

### ISSUE THREAD

**Issue by loicdescotte** [graphql/graphql.github.io#852]
Sangria is no longer developed, and Caliban is on the other hand very active  : https://github.com/ghostdogpr/caliban

**Comment by gabizou** [comment]
Considering https://sangria-graphql.org/ has apparently lapsed in regards to its domain registration, I'd be looking at the docs being updated maybe to even mention that sangria is legacy and no longer actively maintained?

**Comment by sarveshseri** [comment]
After the underfortunate passing of Sangria's creator last year. Other contributors have resolved the ownership issues of various resources and they are still trying to resolve the domain ownership issue.

In the mean time the Sangria website is available at [https://sangria.netlify.app/](https://sangria.netlify.app/)

**Comment by carolstran** [comment]
👋🏼 Thanks for the issue! We're currently re-evaluating how we handle contributions to this Code page and pausing any changes until after those decisions are made. So I'm going to mark this as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #911

**Comment by bengraygh** [comment]
Sangria is actively developed, and is used by Twitter. There was a commit by @yanns a few days prior to this issue being opened, and 63 commits subsequently. Twitter have announced their intention to continue to support [it](https://twitter.com/TwitterOSS/status/1171190354642497537?s=20).

It is unfortunate that the domain lapsed for the original documentation site, but that doesn't really warrant removing the library. There's a separate PR to add Caliban. I feel that this issue should be closed, and superseded by #864  .

**Comment by loicdescotte** [comment]
@bengraygh ok, closing it
