### ISSUE TITLE
Remove "graphql-net" from the options for .net libraries

### ISSUE THREAD

**Issue by mxwlf** [graphql/graphql.github.io#854]
Please remove [graphql-net](https://github.com/chkimes/graphql-net) from the option list for .Net libraries. : https://graphql.github.io/code/#c-net ---> second option

Reasons:

* This library doesn't seem in active development for a long time. PR's are not being reviewed nor Issues addressed.
* It implements an older version of the GraphQL spec.
* It hasn't been migrated to .Net core and it requires substantial work to do so, given the current reliance on a Windows-only API, which makes it not portable to .Net standard targeting.
* Performance issues.
* The idea and offering is attractive in theory, which can draw excitement and start prototyping on it,  just to later find these downsides and realizing how stale it is and the lack of support / maintainers (This is what actually happens to it).

The idea was good and the intentions noble, but at this point its immensely behind other offerings.

Thanks!

P.S. We are re-evaluating our strategy and we will be looking at other options, so if you wish, I can suggest other libraries to compensate for the removal.

**Comment by carolstran** [comment]
👋🏼 Thanks for the issue! We're currently re-evaluating how we handle contributions to this Code page and pausing any changes until after those decisions are made. So I'm going to mark this as `On hold` and if you have any thoughts on this topic, it'd be great if you could voice them in #911

**Comment by orta** [comment]
Doesn't look like this should be removed IMO, the project has a lot of activity https://github.com/graphql-dotnet/graphql-dotnet/graphs/contributors
