### ISSUE TITLE
Sample code is incorrect (generates errors)

### ISSUE THREAD

**Issue by jbrown123** [graphql/graphql.github.io#895]
The sample code on several pages is incorrect (generates runtime errors).
```
app.use('/graphql', graphqlHTTP({
                    ^

TypeError: graphqlHTTP is not a function
```

The following pages are affected:
* Passing Arguments
* Object Types
* Mutations and input types

You left out the brackets around the graphqlHTTP variable.

You have
```
var graphqlHTTP = require('express-graphql');
```

Should be
```
var { graphqlHTTP } = require('express-graphql');
```

If I find more instances of this same mistake, I'll update this issue.

**Comment by IvanGoncharov** [comment]
Fixed in #899
