### ISSUE TITLE
Prefetch Google fonts in Gatsby site

### ISSUE THREAD

**Issue by carolstran** [graphql/graphql.github.io#932]
There was a discussion in #924 about whether we should import or prefetch the Google fonts used for the website. This PR was to the new Gatsby version of graphql.org. 

A few options were proposed/explored:
* Importing the fonts via CSS (which was proposed in the original PR)
* Prefetching with [`gatsby-plugin-prefetch-google-fonts`](https://www.gatsbyjs.com/plugins/gatsby-plugin-prefetch-google-fonts/) (but unfortunately it has been [archived](https://github.com/escaladesports/legacy-gatsby-plugin-prefetch-google-fonts))
* Prefetching with a [community fork of the above package](https://www.npmjs.com/package/@el7cosmos/gatsby-plugin-prefetch-google-fonts) (but [ran into errors](https://github.com/graphql/graphql.github.io/pull/924#issuecomment-708862739))

Ultimately, we decided to import the fonts and then optimize performance/implement prefetching in a future PR. So this issue serves as a reminder for that 😇

**Comment by saihaj** [comment]
As discussed in this issue https://github.com/gatsbyjs/gatsby/issues/10475#issuecomment-447460214 we should host the font in `static` dir and then to preload them we can use [`gatsby-plugin-preload-fonts`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-preload-fonts#readme)

**Comment by mikeesto** [comment]
https://github.com/graphql/graphql.github.io/pull/938 uses [gatsby-plugin-webfonts](https://www.gatsbyjs.com/plugins/gatsby-plugin-webfonts/) (there are so many font plugins 😅 ) to self host the fonts so I think this can be closed now.

**Comment by Urigo** [comment]
Thanks @mikeesto !
closing
