### ISSUE TITLE
Please add a link to a new GraphQL server implementation for .NET

### ISSUE THREAD

**Issue by rivantsov** [graphql/graphql.github.io#941]
NGraphQL: 
https://github.com/rivantsov/ngraphql

on this page: 
https://graphql.org/code/#c-net

thank you

**Comment by carolstran** [comment]
👋🏼  Thanks for opening an issue! Feel free to open a PR adding the NGraphQL link to the Code page 😊

**Comment by rivantsov** [comment]
thank you - just did!

**Comment by rivantsov** [comment]
the page had been redesigned and the link to NGraphQL is not carried over. Is it just overlook or there's a reason? I can resubmit PR for new page.
thanks

**Comment by orta** [comment]
Mistake!

**Comment by rivantsov** [comment]
will you fix it pls?

**Comment by orta** [comment]
Sure, I can merge a PR 👍🏻

**Comment by rivantsov** [comment]
all right, will make a PR, thanks!

**Comment by rivantsov** [comment]
added a PR: 
https://github.com/graphql/graphql.github.io/pull/976
please merge.
thank you

**Comment by orta** [comment]
That's in
