### ISSUE TITLE
Sidebar entries are duplicated on learn page

### ISSUE THREAD

**Issue by mikeesto** [graphql/graphql.github.io#947]
Visible in the sidebar on the [/learn](https://graphql.org/learn/) page. There are many duplications, the screenshot doesn't do it justice.

<img width="183" alt="Screen Shot 2020-11-03 at 3 45 21 pm" src="https://user-images.githubusercontent.com/21051488/97953338-df8cd180-1deb-11eb-96c2-c015fea202ad.png">

**Comment by taylorreece** [comment]
`source` branch is fixed by https://github.com/graphql/graphql.github.io/pull/938/commits/9cb51ac600eff2745ebb91dee91ba57dbbc3cb7c

I imagine they just need to deploy the site to fix the issue.

**Comment by Urigo** [comment]
merged and deployed.
Please check in a couple of minutes and let me know if the issue persists.
Thank you so much for reporting!
