### ISSUE TITLE
Menu overflowing on mobile viewports

### ISSUE THREAD

**Issue by mikeesto** [graphql/graphql.github.io#955]
<img width="413" alt="Screen Shot 2020-11-07 at 12 10 46 pm" src="https://user-images.githubusercontent.com/21051488/98429525-e02aae00-20f2-11eb-8ad9-e9b899c02002.png">

It might be worth looking at using a hamburger menu (or similar) for mobile.

**Comment by rt1301** [comment]
Is this issue open? I would like to work on it

**Comment by mikeesto** [comment]
Hi @rt1301 . Carolyn has made some progress on this: https://github.com/graphql/graphql.github.io/pull/957 . There still might be an opportunity to look at implementing a burger menu though!

**Comment by carolstran** [comment]
Ah sweet @mikeesto, I didn't even realize there was an issue open for this! It was bugging me while I was working on a different part of the site 😆  I merged my fix but yeah if you'd be interested in implementing a burger menu @rt1301 (or especially finding a way to keep the search bar visible at various viewpoints), that'd be amazing 🤩

**Comment by rt1301** [comment]
@carolstran Ok I'll work on these features. Thanks!

**Comment by rt1301** [comment]
@carolstran I have made the PR with the required changes, please have a look. Thanks!

**Comment by Urigo** [comment]
let's track over the PR itself
