### ISSUE TITLE
List of python libraries on code page

### ISSUE THREAD

**Issue by meitros** [graphql/graphql.github.io#959]
Hey - I saw on another issue that this is on hold pending #911, but wanted to open an issue for the python list. It only lists one library (Graphene), and the maintainer of graphene just quit leaving it currently unowned (https://github.com/graphql-python/graphene/issues/1127.)

I think it would be nice to have at least one actively-being-worked-on entry for writing a graphql server in python (Ariadne, maybe?)

**Comment by carolstran** [comment]
Hey @meitros, thanks for opening an issue! Also a good reminder that I need to update #911. While we're still debating a new code page in #936, you can already start adding libraries to the existing list. Feel free to open a PR with your additions 😊

**Comment by patrick91** [comment]
I think this can be closed, there seem to be all the python libraries added to the site :)

**Comment by meitros** [comment]
Wow, nice job with the new page!
