### ISSUE TITLE
Dark Theme planned

### ISSUE THREAD

**Issue by lmeysel** [graphql/graphql.github.io#961]
Is there a dark theme planned? How are chances it will be implemented?

**Comment by Urigo** [comment]
We would love to review PRs and contributions!

**Comment by orta** [comment]
Any implementation should avoid flashing, would recommend following this: https://joshwcomeau.com/gatsby/dark-mode/

**Comment by rt1301** [comment]
Is this issue open? If possible I would like to work on this

**Comment by lmeysel** [comment]
...at least i am not working on it

**Comment by Tobertet** [comment]
This would be awesome, my eyes burned when I tried to read the docs

**Comment by Urigo** [comment]
We now have dark mode thanks to @dimaMachina's refactoring to Nextra!
