### ISSUE TITLE
Continuously updating dependencies

### ISSUE THREAD

**Issue by Urigo** [graphql/graphql.github.io#975]
I'm in favor of setting up renovate or dependebot so we'll keep up to date with dev dependencies versions and won't fall behind like before..

@orta @ardatan @carolstran thoughts?

**Comment by orta** [comment]
Happy to have them turned on, but I have all these types of bots removed from all my notifications because I think it's far too much noise for the little value they give. So, someone else will need to handle merging and keeping on top of them etc.

**Comment by carolstran** [comment]
Yeah, I also think a bot to monitor dependencies is a good idea!

**Comment by carolstran** [comment]
We got our first dependabot PR since this issue was open (#989) 🤖  🎉 

So what should be the process for merging? Beyond all the builds/tests being green.

**Comment by Urigo** [comment]
done
